### ISSUE TITLE
Password Generator

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-extension#19]
We need a password generator screen. It should contain:

Password input (always visible)
Refresh button
Copy button
Length input number box (in the future it can be scroll)
Numbers checkbox
Symbols checkbox

Also we should save the settings here at storage.

**Comment by yakuter** [comment]
Hey @izniburak do you want to work on this?

**Comment by izniburak** [comment]
Hi @yakuter , I'm in for it. I guess I can try to make something about it :)

**Comment by yakuter** [comment]
Ok thank you :)
