### ISSUE TITLE
Urgent: Subscription settings needed.

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-extension#9]
Can we add subscription settings as in the picture @bufgix ? There is all ready logout there. We just need to add the others.
![Screen Shot 2021-03-13 at 10 27 18](https://user-images.githubusercontent.com/3696314/111022914-f28d5f00-83e6-11eb-8389-86e896d62b22.png)

**Comment by bufgix** [comment]
👍

**Comment by bufgix** [comment]
done !
